// This file is @generated by prost-build.
/// Only Assertion travels before encryption. All Record fields are encrypted.
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Assertion {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub evidence: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "3")]
    pub profile: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Header {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct Start {
    #[prost(string, tag = "1")]
    pub method: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub path: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub headers: ::prost::alloc::vec::Vec<Header>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Data {
    #[prost(uint64, tag = "1")]
    pub index: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub body: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct End {
    #[prost(uint64, tag = "1")]
    pub length: u64,
    #[prost(bytes = "vec", tag = "2")]
    pub sha256: ::prost::alloc::vec::Vec<u8>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct Response {
    #[prost(uint32, tag = "1")]
    pub status: u32,
    #[prost(message, repeated, tag = "2")]
    pub headers: ::prost::alloc::vec::Vec<Header>,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Completion {
    #[prost(message, optional, tag = "1")]
    pub body: ::core::option::Option<End>,
    #[prost(string, tag = "2")]
    pub receipt_id: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "3")]
    pub receipt: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub session: ::prost::alloc::vec::Vec<u8>,
}
#[derive(
    serde::Serialize, serde::Deserialize, Clone, Copy, PartialEq, Eq, Hash, ::prost::Message,
)]
pub struct Empty {}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Failure {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
}
#[derive(
    serde::Serialize, serde::Deserialize, Clone, Copy, PartialEq, Eq, Hash, ::prost::Message,
)]
pub struct Credit {
    #[prost(uint32, tag = "1")]
    pub bytes: u32,
}
#[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Message)]
pub struct Record {
    #[prost(uint32, tag = "1")]
    pub version: u32,
    #[prost(bytes = "vec", tag = "2")]
    pub id: ::prost::alloc::vec::Vec<u8>,
    #[prost(
        oneof = "record::Kind",
        tags = "3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14"
    )]
    pub kind: ::core::option::Option<record::Kind>,
}
/// Nested message and enum types in `Record`.
pub mod record {
    #[derive(serde::Serialize, serde::Deserialize, Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag = "3")]
        RequestStart(super::Start),
        #[prost(message, tag = "4")]
        RequestData(super::Data),
        #[prost(message, tag = "5")]
        RequestEnd(super::End),
        #[prost(message, tag = "6")]
        ResponseStart(super::Response),
        #[prost(message, tag = "7")]
        ResponseData(super::Data),
        #[prost(message, tag = "8")]
        ResponseEnd(super::Completion),
        #[prost(message, tag = "9")]
        Cancel(super::Empty),
        #[prost(message, tag = "10")]
        Cancelled(super::Empty),
        #[prost(message, tag = "11")]
        Failure(super::Failure),
        #[prost(message, tag = "12")]
        UploadCredit(super::Credit),
        #[prost(message, tag = "13")]
        ResponseCredit(super::Credit),
        #[prost(message, tag = "14")]
        TerminalAck(super::Empty),
    }
}
